Augment trigger error messages with context identifying the trigger
This patch adds an error context callback so that ereport() and
elog() messages while executing a trigger function will now have
a "CONTEXT:" line showing the trigger name, event type, table
name and function name.  The new context messages are not
displayed for the "internal" or "system" triggers used to
implement referential constraints.

This patch is based on PostgreSQL version
REL9_2_4 (commit 73c122769ca1f49c451e315d476c80fdcf9f20cc).

Example...
  create trigger check_fkeys2_fkey_restrict
      before delete or update on fkeys2
      for each row
      execute procedure
          check_foreign_key(1,'restrict','pkey23','fkeys','fkey3');
  insert into fkeys2 values (70, '5', 3);
  ERROR:  tuple references non-existent key
  DETAIL:  Trigger "check_fkeys2_pkey_exist" found tuple referencing
      non-existent key in "pkeys".
  CONTEXT:  Trigger "check_fkeys2_pkey_exist" before insert "fkeys2"
      procedure check_primary_key()
  update pkeys set pkey1 = 7, pkey2 = '70' where pkey1 = 10';
  NOTICE:  check_pkeys_fkey_cascade: 1 tuple(s) of fkeys are deleted
  CONTEXT:  Trigger "check_pkeys_fkey_cascade" before update "pkeys"
      procedure check_foreign_key()
  NOTICE:  check_pkeys_fkey_cascade: 1 tuple(s) of fkeys2 are deleted
  CONTEXT:  Trigger "check_pkeys_fkey_cascade" before update "pkeys"
      procedure check_foreign_key()